// Skema form aturan — sumber tunggal untuk halaman Aturan dan aturan per-target.
// `when` menentukan kapan sebuah field relevan; field yang tidak relevan disembunyikan.
export const SCHEMA = [
  { group: 'Ukuran posisi', icon: 'ti-ruler', fields: [
    { path: 'sizing.mode', label: 'Cara menentukan ukuran', type: 'select', options: [
      ['mirror', 'Sama persis dengan target'], ['pct', 'Persen dari target'],
      ['multiplier', 'Kelipatan dari target'], ['fixed_quote', 'Nominal tetap']],
      help: 'mirror = likuiditas identik; pct/multiplier = skala; nominal tetap = modal sama tiap posisi' },
    { path: 'sizing.pct', label: 'Persen dari target (%)', type: 'number', step: 1, when: (r) => r.sizing.mode === 'pct' },
    { path: 'sizing.multiplier', label: 'Kelipatan', type: 'number', step: 0.1, when: (r) => r.sizing.mode === 'multiplier' },
    { path: 'sizing.fixed_quote_usd', label: 'Nominal tetap (USD)', type: 'number', step: 5, when: (r) => r.sizing.mode === 'fixed_quote',
      help: 'dipakai di pool berkuotasi USDG' },
    { path: 'sizing.fixed_quote_eth', label: 'Nominal tetap (ETH)', type: 'number', step: 0.005, when: (r) => r.sizing.mode === 'fixed_quote',
      help: 'dipakai di pool berkuotasi ETH/WETH' },
    { path: 'sizing.min_quote_usd', label: 'Minimum per posisi (USD)', type: 'number', step: 1 },
    { path: 'sizing.force_min', label: 'Paksa masuk kalau di bawah minimum', type: 'bool',
      help: 'Mati = posisi dilewati; nyala = ukurannya dinaikkan ke nominal paksa' },
    { path: 'sizing.force_min_usd', label: 'Nominal paksa (USD)', type: 'number', step: 5, when: (r) => r.sizing.force_min },
    { path: 'sizing.max_quote_per_position_usd', label: 'Maksimum per posisi (USD)', type: 'number', step: 10 },
    { path: 'sizing.max_total_exposure_usd', label: 'Batas eksposur total (USD)', type: 'number', step: 50 },
    { path: 'sizing.daily_budget_usd', label: 'Anggaran per hari (USD)', type: 'number', step: 50 },
  ] },
  { group: 'Rentang harga', icon: 'ti-arrows-horizontal', fields: [
    { path: 'range.mode', label: 'Cara menentukan rentang', type: 'select', options: [
      ['exact', 'Sama persis dengan target'], ['recenter', 'Lebar sama, dipusatkan harga kini'],
      ['scale', 'Lebar dikali faktor'], ['width_pct', 'Lebar tetap ±%'], ['full', 'Full range']] },
    { path: 'range.scale', label: 'Faktor lebar', type: 'number', step: 0.1, when: (r) => r.range.mode === 'scale' },
    { path: 'range.width_pct', label: 'Lebar ±%', type: 'number', step: 1, when: (r) => r.range.mode === 'width_pct' },
    { path: 'range.min_width_ticks', label: 'Lebar minimum (tick)', type: 'number', step: 10, when: (r) => r.range.mode !== 'full' },
    { path: 'range.align', label: 'Pembulatan tick', type: 'select', options: [
      ['nearest', 'Ke yang terdekat'], ['down', 'Ke bawah'], ['up', 'Ke atas']],
      help: 'Tick harus kelipatan tickSpacing pool; ini menentukan arah pembulatannya', when: (r) => r.range.mode !== 'exact' },
  ] },
  { group: 'Posisi satu sisi', icon: 'ti-arrow-bar-to-right', fields: [
    { path: 'onesided.policy', label: 'Kalau rentang di luar harga kini', type: 'select', options: [
      ['copy', 'Tetap salin (jadi limit order)'], ['skip', 'Lewati'], ['recenter', 'Geser ke harga kini']],
      help: 'Rentang yang seluruhnya di atas/bawah harga = posisi satu token saja' },
    { path: 'onesided.max_quote_usd', label: 'Batas nominal satu sisi (USD)', type: 'number', step: 10, when: (r) => r.onesided.policy !== 'skip' },
  ] },
  { group: 'Auto-swap', icon: 'ti-refresh', fields: [
    { path: 'swap.enabled', label: 'Tukar otomatis kalau token kurang', type: 'bool' },
    { path: 'swap.max_slippage_bps', label: 'Slippage maksimum (bps)', type: 'number', step: 10, when: (r) => r.swap.enabled },
    { path: 'swap.max_price_impact_bps', label: 'Dampak harga maksimum (bps)', type: 'number', step: 10, when: (r) => r.swap.enabled },
  ] },
  { group: 'Keluar', icon: 'ti-door-exit', fields: [
    { path: 'exit.follow_target', label: 'Ikut keluar saat target keluar', type: 'bool' },
    { path: 'exit.follow_partial', label: 'Ikut menarik sebagian (proporsional)', type: 'bool', when: (r) => r.exit.follow_target },
    { path: 'exit.out_of_range_minutes', label: 'Tutup kalau di luar rentang selama (menit, 0=mati)', type: 'number', step: 5 },
    { path: 'exit.out_of_range_pct', label: 'Tutup kalau harga lebih dari (%) di luar rentang (0=mati)', type: 'number', step: 5 },
    { path: 'exit.reenter_within_pct', label: 'Buka lagi kalau harga kembali ≤ (%) dari rentang (0=mati)', type: 'number', step: 5, when: (r) => r.exit.out_of_range_pct > 0 },
    { path: 'exit.stop_loss_pct', label: 'Stop loss (%, 0=mati)', type: 'number', step: 1 },
    { path: 'exit.take_profit_pct', label: 'Take profit (%, 0=mati)', type: 'number', step: 1 },
    { path: 'exit.max_age_hours', label: 'Umur maksimum (jam, 0=mati)', type: 'number', step: 1 },
    { path: 'exit.sell_leftover', label: 'Jual memecoin sisa setelah keluar', type: 'bool',
      help: 'Token yang diterima saat menutup posisi dijual balik ke USDG/ETH lewat agregator Kyber' },
    { path: 'exit.sell_max_loss_bps', label: 'Batas rugi jual sisa (bps)', type: 'number', step: 100, when: (r) => r.exit.sell_leftover,
      help: 'Fee pool + dampak harga. Di atas batas ini token disimpan dan dikutip ulang terus sampai lolos' },
    { path: 'exit.leftover_retry_sec', label: 'Cek ulang sisa tiap (detik)', type: 'number', step: 1, when: (r) => r.exit.sell_leftover,
      help: 'Satu kutipan Kyber per token per interval; swap hanya dikirim kalau ruginya sudah di bawah batas. Minimal 1 — terlalu rapat bisa kena batas laju Kyber yang juga dipakai zap' },
  ] },
  { group: 'Saringan', icon: 'ti-filter', fields: [
    { path: 'filters.allow_hooks', label: 'Izinkan pool v4 dengan hook', type: 'bool', help: 'Hook bisa memblokir penarikan — default: tolak' },
    { path: 'filters.min_target_quote_usd', label: 'Abaikan posisi target di bawah (USD)', type: 'number', step: 5 },
    { path: 'filters.max_open_positions', label: 'Maksimum posisi terbuka', type: 'number', step: 1 },
    { path: 'filters.cooldown_seconds', label: 'Jeda antar salinan di pool sama (detik)', type: 'number', step: 5 },
    { path: 'filters.min_pool_age_minutes', label: 'Umur pool minimum (menit)', type: 'number', step: 5, help: 'Pool yang baru dibuat sering jebakan; 0 = mati' },
    { path: 'filters.max_fee_bps', label: 'Batas fee pool', type: 'number', step: 1000, help: 'Dalam satuan fee Uniswap: 3000 = 0,3%, 100000 = 10%' },
    { path: 'filters.quote_whitelist', label: 'Aset kuotasi diizinkan', type: 'list' },
    { path: 'filters.venues', label: 'Venue diizinkan', type: 'list' },
    { path: 'filters.token_blacklist', label: 'Daftar hitam token (alamat, pisah koma)', type: 'list' },
    { path: 'filters.token_whitelist', label: 'Daftar putih token (kosong = semua)', type: 'list' },
  ] },
];

export const RULE_HELP = {
  "sizing.mode": "Tentukan modal awal salinan: likuiditas sama, persentase, kelipatan, atau nominal tetap. Hasilnya tetap dibatasi batas per posisi, eksposur, anggaran harian, dan saldo.",
  "sizing.pct": "50 berarti menyalin 50% likuiditas target; 100 berarti sama dengan target, sebelum batas modal diterapkan.",
  "sizing.multiplier": "0,5 berarti setengah likuiditas target; 2 berarti dua kali lipat, sebelum batas modal diterapkan.",
  "sizing.min_quote_usd": "Jika nilai salinan setelah pembatasan lebih kecil dari angka ini, posisi dilewati. Ini bukan modal yang otomatis ditambahkan.",
  "sizing.force_min": "Kalau ukuran hasil hitung lebih kecil dari minimum, posisi tidak dilewati melainkan dinaikkan ke nominal paksa. Batas per posisi, eksposur, anggaran harian, dan saldo tetap berlaku.",
  "sizing.force_min_usd": "Nominal yang dipakai saat paksa masuk aktif. Contoh: 10% dari target $250 = $25, minimum $100, nominal paksa $100 → posisi dibuka $100. Kalau nominal ini tidak muat di batas yang tersisa, posisi tetap dilewati.",
  "sizing.max_quote_per_position_usd": "Modal maksimum untuk satu posisi salinan. Ukuran yang lebih besar diperkecil agar sesuai batas. Nilai 0 tidak berarti tanpa batas.",
  "sizing.max_total_exposure_usd": "Batas modal gabungan posisi terbuka. Sisa jatah dihitung setelah dikurangi eksposur yang sudah terbuka. Nilai 0 menghentikan penambahan modal.",
  "sizing.daily_budget_usd": "Batas modal masuk per hari. Jika jatah habis, salinan baru dilewati; ini bukan batas kerugian harian.",
  "range.mode": "Pilih rentang harga tempat likuiditas bekerja: ikuti target, pusatkan ulang, ubah lebar, gunakan persentase, atau seluruh rentang. Posisi di luar rentang hanya berisi satu token.",
  "range.scale": "Mengalikan lebar rentang target dengan faktor ini, dengan titik tengah target tetap. 2 berarti dua kali lebih lebar.",
  "range.width_pct": "Lebar dihitung dari harga kini dalam tick logaritmik lalu dibulatkan ke tick pool. Batas harga akhir dapat berbeda dari persentase sederhana.",
  "range.min_width_ticks": "Memperlebar rentang yang lebih sempit dari jumlah tick ini. Tick adalah langkah harga Uniswap, bukan persen. 0 = tanpa lebar minimum.",
  "onesided.max_quote_usd": "Batas modal untuk posisi yang hanya berisi satu token. Batas per posisi dan sisa anggaran tetap berlaku.",
  "swap.enabled": "Mengizinkan pertukaran token untuk menyiapkan aset posisi saat saldo token kurang. Pertukaran mengikuti batas slippage dan dampak harga.",
  "swap.max_slippage_bps": "Selisih harga yang diizinkan saat eksekusi dibanding kutipan. 100 bps = 1%; 50 bps = 0,5%.",
  "swap.max_price_impact_bps": "Batas perubahan harga yang disebabkan ukuran swap itu sendiri. 100 bps = 1%. Berbeda dari slippage saat eksekusi.",
  "exit.follow_target": "Bot ikut menutup salinan ketika target keluar dari posisi. Aturan keluar mandiri di bawah tetap terpisah.",
  "exit.follow_partial": "Saat target menarik sebagian likuiditas, bot menarik bagian yang sebanding dari salinannya.",
  "exit.out_of_range_minutes": "Tutup posisi setelah terus berada di luar rentang selama durasi ini. Penghitung direset ketika kembali masuk rentang. 0 = nonaktif.",
  "exit.out_of_range_pct": "Tutup posisi begitu harga lebih jauh dari persentase ini di luar rentang — jarak ke tepi terdekat, angka yang sama dengan \"di luar · 61% di atas\" di daftar posisi. Modal tidak menganggur di posisi yang jauh dari harga. Berlaku juga saat masuk: entry target yang rentangnya sejauh ini ditunda, bukan disalin. Dua sinkron berturut-turut (~1 menit) sebelum ditutup. 0 = nonaktif.",
  "exit.reenter_within_pct": "Cermin yang ditunda atau ditutup karena jauh dibuka lagi begitu harga kembali sedekat ini dari rentang, selama posisi target masih terbuka. Ukurannya dihitung ulang dari likuiditas target saat itu. Harus lebih kecil dari ambang tutup supaya tidak buka-tutup di satu harga. 0 = nonaktif.",
  "exit.stop_loss_pct": "Memicu penutupan ketika PnL posisi mencapai persentase rugi ini. Isi angka positif, misalnya 10 untuk rugi 10%. Harga eksekusi akhir bisa berbeda. 0 = nonaktif.",
  "exit.take_profit_pct": "Memicu penutupan ketika PnL posisi mencapai persentase untung ini. Harga eksekusi akhir bisa berbeda. 0 = nonaktif.",
  "exit.max_age_hours": "Tutup posisi setelah umur posisi mencapai jumlah jam ini, terlepas dari laba atau rugi. 0 = nonaktif.",
  "filters.min_target_quote_usd": "Lewati posisi target yang nilainya lebih kecil dari angka ini, sebelum ukuran salinan dihitung.",
  "filters.max_open_positions": "Batasi jumlah posisi bot yang boleh terbuka bersamaan.",
  "filters.cooldown_seconds": "Jeda sebelum menyalin lagi di pool yang sama, untuk menghindari salinan yang terlalu rapat.",
  "filters.quote_whitelist": "Pisahkan dengan koma, misalnya USDG, ETH, WETH. Kosong berarti semua aset kuotasi yang dikenali bot.",
  "filters.venues": "Pisahkan dengan koma: v3, v4. Gunakan huruf kecil. Daftar kosong tidak mengizinkan venue mana pun.",
  "filters.token_blacklist": "Alamat token yang selalu ditolak. Pisahkan alamat dengan koma. Daftar hitam mengalahkan daftar putih.",
  "filters.token_whitelist": "Hanya izinkan alamat token dalam daftar ini. Pisahkan dengan koma. Kosong berarti tidak membatasi token melalui daftar putih."
};
